'''
    Event called when a unhandled exception raised
'''

from __main__ import bot

import discord

#@bot.event
async def on_error( event: str, *args, **kwargs):
    pass
